package com.agentdesk.controller;

import com.agentdesk.api.ApiModels.*;
import com.agentdesk.security.AuthContext;
import com.agentdesk.security.PasswordService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import com.agentdesk.service.AuditService;

import java.util.*;

@RestController
@RequestMapping("/api/admin")
public class AdminController {
  private final JdbcTemplate jdbc; private final AuthContext auth; private final PasswordService passwords; private final AuditService audit; private final com.agentdesk.service.NotificationService notifications;
  public AdminController(JdbcTemplate jdbc,AuthContext auth,PasswordService passwords,AuditService audit,com.agentdesk.service.NotificationService notifications){this.jdbc=jdbc;this.auth=auth;this.passwords=passwords;this.audit=audit;this.notifications=notifications;}
  @GetMapping("/users") public List<Map<String,Object>> users(HttpServletRequest req){auth.requireAdmin(auth.current(req));return jdbc.queryForList("SELECT u.id,u.username,u.display_name,u.department_id,d.name AS department,u.active,u.account_status,u.force_password_change,COALESCE(r.code,'EMPLOYEE') AS role,u.created_at FROM users u LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id ORDER BY u.id");}
  @PostMapping("/users") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> createUser(@Valid @RequestBody UserCreateRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);if(body.password().length()<8)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"密码至少 8 位");if(jdbc.queryForObject("SELECT count(*) FROM departments WHERE id=?",Integer.class,body.departmentId())==0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"部门不存在");if(!Set.of("ADMIN","AGENT","EMPLOYEE").contains(body.role()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"角色不合法");if(jdbc.queryForObject("SELECT count(*) FROM users WHERE username=?",Integer.class,body.username())>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"用户名已存在");Long id=jdbc.queryForObject("INSERT INTO users(username,display_name,department_id,password_hash,account_status,force_password_change) VALUES (?,?,?,?,'ACTIVE',true) RETURNING id",Long.class,body.username(),body.displayName(),body.departmentId(),passwords.hash(body.password()));setRole(id,body.role());audit.log(actor.id(),"USER_CREATED","USER",id,Map.of("role",body.role()));return Map.of("id",id,"message","用户已创建");}
  @PostMapping("/users/{id}/approve") public Map<String,Object> approve(@PathVariable long id,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);jdbc.update("UPDATE users SET account_status='ACTIVE',active=true,force_password_change=true WHERE id=?",id);audit.log(actor.id(),"USER_APPROVED","USER",id,Map.of());notifications.notify(id,"ACCOUNT_APPROVED","你的账号已开通，请使用初始密码登录并修改","/login","USER",id,null);return Map.of("id",id,"accountStatus","ACTIVE");}
  @PatchMapping("/users/{id}") public Map<String,Object> updateUser(@PathVariable long id,@RequestBody UserUpdateRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);if(body.departmentId()!=null)jdbc.update("UPDATE users SET department_id=? WHERE id=?",body.departmentId(),id);if(body.active()!=null)jdbc.update("UPDATE users SET active=?,account_status=? WHERE id=?",body.active(),body.active()?"ACTIVE":"DISABLED",id);if(body.accountStatus()!=null)jdbc.update("UPDATE users SET account_status=?,active=? WHERE id=?",body.accountStatus(),"ACTIVE".equals(body.accountStatus()),id);if(body.role()!=null)setRole(id,body.role());audit.log(actor.id(),"USER_UPDATED","USER",id,Map.of());return Map.of("id",id,"updated",true);}
  @PostMapping("/users/{id}/reset-password") public Map<String,Object> resetPassword(@PathVariable long id,@Valid @RequestBody ResetPasswordRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);jdbc.update("UPDATE users SET password_hash=?,force_password_change=true WHERE id=?",passwords.hash(body.password()),id);audit.log(actor.id(),"USER_PASSWORD_RESET","USER",id,Map.of());return Map.of("id",id,"message","密码已重置");}
  @GetMapping("/departments") public List<Map<String,Object>> departments(HttpServletRequest req){auth.requireAdmin(auth.current(req));return jdbc.queryForList("SELECT id,name,created_at FROM departments ORDER BY id");}
  @PostMapping("/departments") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> createDepartment(@Valid @RequestBody DepartmentRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);Long id=jdbc.queryForObject("INSERT INTO departments(name) VALUES (?) RETURNING id",Long.class,body.name());audit.log(actor.id(),"DEPARTMENT_CREATED","DEPARTMENT",id,Map.of("name",body.name()));return Map.of("id",id,"name",body.name());}
  @PatchMapping("/departments/{id}") public Map<String,Object> updateDepartment(@PathVariable long id,@Valid @RequestBody DepartmentRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);jdbc.update("UPDATE departments SET name=? WHERE id=?",body.name(),id);audit.log(actor.id(),"DEPARTMENT_UPDATED","DEPARTMENT",id,Map.of("name",body.name()));return Map.of("id",id,"name",body.name());}
  @GetMapping("/queues") public List<Map<String,Object>> queues(HttpServletRequest req){auth.requireAdmin(auth.current(req));return jdbc.queryForList("SELECT q.id,q.code,q.name,q.description,q.active,q.created_at,COUNT(qm.user_id) AS member_count FROM support_queues q LEFT JOIN queue_members qm ON qm.queue_id=q.id GROUP BY q.id ORDER BY q.id");}
  @PostMapping("/queues") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> createQueue(@Valid @RequestBody QueueRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);Long id=jdbc.queryForObject("INSERT INTO support_queues(code,name,description,active) VALUES (?,?,?,COALESCE(?,true)) RETURNING id",Long.class,body.code(),body.name(),body.description(),body.active());audit.log(actor.id(),"QUEUE_CREATED","QUEUE",id,Map.of("code",body.code()));return Map.of("id",id,"code",body.code());}
  @PatchMapping("/queues/{id}") public Map<String,Object> updateQueue(@PathVariable long id,@RequestBody QueueRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);jdbc.update("UPDATE support_queues SET name=COALESCE(?,name),description=COALESCE(?,description),active=COALESCE(?,active) WHERE id=?",body.name(),body.description(),body.active(),id);audit.log(actor.id(),"QUEUE_UPDATED","QUEUE",id,Map.of());return Map.of("id",id,"updated",true);}
  @GetMapping("/queues/{id}/members") public List<Map<String,Object>> members(@PathVariable long id,HttpServletRequest req){auth.requireAdmin(auth.current(req));return jdbc.queryForList("SELECT u.id,u.username,u.display_name,u.department_id FROM users u JOIN queue_members qm ON qm.user_id=u.id WHERE qm.queue_id=? ORDER BY u.id",id);}
  @PostMapping("/queues/{id}/members") public Map<String,Object> addMember(@PathVariable long id,@Valid @RequestBody QueueMemberRequest body,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);jdbc.update("INSERT INTO queue_members(queue_id,user_id) VALUES (?,?) ON CONFLICT DO NOTHING",id,body.userId());audit.log(actor.id(),"QUEUE_MEMBER_ADDED","QUEUE",id,Map.of("userId",body.userId()));return Map.of("queueId",id,"userId",body.userId(),"member",true);}
  @DeleteMapping("/queues/{id}/members/{userId}") public Map<String,Object> removeMember(@PathVariable long id,@PathVariable long userId,HttpServletRequest req){UserContext actor=auth.current(req);auth.requireAdmin(actor);jdbc.update("DELETE FROM queue_members WHERE queue_id=? AND user_id=?",id,userId);audit.log(actor.id(),"QUEUE_MEMBER_REMOVED","QUEUE",id,Map.of("userId",userId));return Map.of("queueId",id,"userId",userId,"member",false);}
  private void setRole(long id,String role){if(!Set.of("ADMIN","AGENT","EMPLOYEE").contains(role))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"角色不合法");jdbc.update("DELETE FROM user_roles WHERE user_id=?",id);jdbc.update("INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code=?",id,role);}
}
